const arr = [1,2,3,4]
const arr2 = new Array(5)
console.log(arr)
console.log(arr2)
console.log(arr2[2])
const arr3 = Array.from("hello")
console.log(arr3)
arr3[arr3.length + 5] = "test"
console.log(arr3)
arr3.push(4)
console.log(arr3)
arr3.pop()
console.log(arr3)
arr3.shift()
console.log(arr3)
arr3.unshift("hi")
console.log(arr3)
console.log(arr3.indexOf("o"))
console.log(arr3.lastIndexOf("l"))
console.log(arr3.includes("l"))

const arr4 = arr.concat(arr3)
console.log(arr4)
const str = arr.join("|")
console.log(str)
const slicee = arr.slice(1,3)
console.log(slicee)
const splicee = arr.splice(1,2)
console.log(arr)